Use nix develop instead of nix-shell
nix-shell produces:

nix-shell ghc.nix
error: nix-shell requires a single derivation
Try 'nix-shell --help' for more information.

presumably due to the flake,
I think it's safe to use flakes by default these days however.